python ./preprocess_data.py \
        --input ./dataset/pe-nlp/train-00000-of-00001.parquet \
        --tokenizer-name-or-path ./models/Qwen2.5-7B \
        --output-prefix ./dataset/pe-nlp/data \
        --handler-name R1AlpacaStyleInstructionHandler \
        --tokenizer-type PretrainedFromHF \
        --workers 4 \
        --log-interval 1000 \
        --prompt-type qwen_r1 \
        --dataset-additional-keys labels \
        --map-keys '{"prompt":"question", "query":"", "response": "ground_truth_answer", "system":""}' \